dist: trusty
sudo: false
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
      - llvm-toolchain-trusty-3.9
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-6
      - g++-6
      - clang-3.9
env:
  - CCMP=gcc-4.9 CXXCMP=g++-4.9
  - CCMP=gcc-6 CXXCMP=g++-6
  - CCMP=clang-3.9 CXXCMP=clang++-3.9
before_install:
  - bash scripts/install_deps.sh
  - export PATH="$HOME/deps/cmake/bin":"$PATH"
  - export CC=$CCMP
  - export CXX=$CXXCMP
cache:
  directories:
    - $HOME/deps
script:
  - mkdir build && cd build && cmake -DBUILD_SINGLE_HEADER=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Wshadow -Werror" .. && make -j2
